# Generated by Django 4.0.4 on 2022-04-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBapp', '0002_remove_posts_text_posts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='State',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
