# Generated by Django 4.0.4 on 2022-04-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBapp', '0003_posts_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Mobile_No',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
